name: Continous Integration

on:
  push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update package definition
      run: sudo apt-get update

    - name: Install X11 headers
      run: sudo apt-get install -y libgl1-mesa-dev xorg-dev

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: false

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
