name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  packages: write

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets: inherit

  create-release:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifcats
        uses: actions/download-artifact@v4

      - name: DELETE_ME
        run: ls -l *

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Essentialist for Linux (amd64)/essentialist-linux,Essentialist for Windows (x64)/essentialist.exe,Essentialist for MacOS (arm64)/essentialist-mac-os-arm64,Essentialist for MacOS (intel)/essentialist-mac-os-intel,Essentialist for Android (APK)/Essentialist.apk"
